"use strict";
// Sinh tồn 2.0.0 — generated from docs/releases/hardcore-2.0.0-spec.md.
const ITEMS = {
  common: [
    {
      id: "rusted_edge",
      name: "Rusted Edge",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 5,
      },
      text: "+5 STR",
      curse: null,
    },
    {
      id: "iron_dagger",
      name: "Iron Dagger",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 1,
        dex: 4,
      },
      text: "+1 STR, +4 DEX",
      curse: null,
    },
    {
      id: "cracked_wand",
      name: "Cracked Wand",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        ene: 5,
      },
      text: "+5 ENE",
      curse: null,
    },
    {
      id: "hunter_bow",
      name: "Hunter Bow",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 5,
      },
      text: "+5 DEX",
      curse: null,
    },
    {
      id: "militia_spear",
      name: "Militia Spear",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 3,
        dex: 2,
      },
      text: "+3 STR, +2 DEX",
      curse: null,
    },
    {
      id: "bone_club",
      name: "Bone Club",
      category: "weapon",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 6,
        dex: -1,
      },
      text: "+6 STR, -1 DEX",
      curse: null,
    },
    {
      id: "dented_plate",
      name: "Dented Plate",
      category: "armor",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 3,
        vit: 2,
      },
      text: "+3 STR, +2 VIT",
      curse: null,
    },
    {
      id: "wooden_buckler",
      name: "Wooden Buckler",
      category: "armor",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 2,
        vit: 2,
        ene: 1,
      },
      text: "+2 STR, +2 VIT, +1 ENE",
      curse: null,
    },
    {
      id: "worn_boots",
      name: "Worn Boots",
      category: "armor",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 4,
      },
      text: "+4 DEX",
      curse: null,
    },
    {
      id: "copper_ring",
      name: "Copper Ring",
      category: "jewelry",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        vit: 1,
        ene: 4,
      },
      text: "+1 VIT, +4 ENE",
      curse: null,
    },
    {
      id: "minor_life_charm",
      name: "Minor Life Charm",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        vit: 5,
      },
      text: "+5 VIT",
      curse: null,
    },
    {
      id: "rabbit_foot",
      name: "Rabbit Foot",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        luck: 1,
      },
      text: "+1 Luck",
      curse: null,
    },
    {
      id: "red_potion_belt",
      name: "Red Potion Belt",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        potions: 1,
      },
      text: "+1 bình khi nhận mỗi cấp",
      curse: null,
    },
    {
      id: "scout_lens",
      name: "Scout Lens",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 2,
        mimicDetection: 0.02,
      },
      text: "+2 DEX · +2% phát hiện Mimic",
      curse: null,
    },
    {
      id: "mana_fragment",
      name: "Mana Fragment",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        ene: 2,
        maxMana: 1,
      },
      text: "+2 ENE · +1 Max MP",
      curse: null,
    },
    {
      id: "battle_token",
      name: "Battle Token",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 2,
        vit: 2,
      },
      text: "+2 STR, +2 VIT",
      curse: null,
    },
    {
      id: "silver_thread",
      name: "Silver Thread",
      category: "jewelry",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 2,
        ene: 3,
      },
      text: "+2 DEX, +3 ENE",
      curse: null,
    },
    {
      id: "traveler_map",
      name: "Traveler Map",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 2,
        luck: 1,
      },
      text: "+2 DEX · +1 Luck",
      curse: null,
    },
    {
      id: "small_ward",
      name: "Small Ward",
      category: "armor",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 2,
        vit: 3,
      },
      text: "+2 STR, +3 VIT",
      curse: null,
    },
    {
      id: "sharpening_stone",
      name: "Sharpening Stone",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 5,
      },
      text: "+5 STR",
      curse: null,
    },
    {
      id: "ember_bead",
      name: "Ember Bead",
      category: "jewelry",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 1,
        ene: 4,
      },
      text: "+1 STR, +4 ENE",
      curse: null,
    },
    {
      id: "fox_mask",
      name: "Fox Mask",
      category: "armor",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 5,
      },
      text: "+5 DEX",
      curse: null,
    },
    {
      id: "oak_talisman",
      name: "Oak Talisman",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        vit: 6,
      },
      text: "+6 VIT",
      curse: null,
    },
    {
      id: "glass_bead",
      name: "Glass Bead",
      category: "jewelry",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 4,
      },
      text: "+4 DEX",
      curse: null,
    },
    {
      id: "field_bandage",
      name: "Field Bandage",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        heal: 10,
      },
      text: "hồi 10 HP khi nhận mỗi cấp",
      curse: null,
    },
    {
      id: "iron_nail",
      name: "Iron Nail",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        str: 3,
        vit: 2,
      },
      text: "+3 STR, +2 VIT",
      curse: null,
    },
    {
      id: "hawk_feather",
      name: "Hawk Feather",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 5,
      },
      text: "+5 DEX",
      curse: null,
    },
    {
      id: "smoke_vial",
      name: "Smoke Vial",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        dex: 5,
      },
      text: "+5 DEX",
      curse: null,
    },
    {
      id: "cold_ash",
      name: "Cold Ash",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        ene: 5,
      },
      text: "+5 ENE",
      curse: null,
    },
    {
      id: "goblin_hook",
      name: "Goblin Hook",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        goblinChance: 0.02,
      },
      text: "+2% bắt Goblin",
      curse: null,
    },
    {
      id: "chest_chalk",
      name: "Chest Chalk",
      category: "utility",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        mimicDetection: 0.03,
      },
      text: "+3% phát hiện Mimic",
      curse: null,
    },
    {
      id: "faded_clover",
      name: "Faded Clover",
      category: "charm",
      rarity: "common",
      typeCode: "R",
      catalogVersion: 2,
      effects: {
        vit: 2,
        luck: 1,
      },
      text: "+2 VIT · +1 Luck",
      curse: null,
    },
  ],
  rare: [
    {
      id: "hunters_fang",
      name: "Hunter’s Fang",
      category: "weapon",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 4,
        dex: 6,
      },
      text: "+4 STR, +6 DEX",
      curse: null,
    },
    {
      id: "runed_carapace",
      name: "Runed Carapace",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        vit: 4,
        ene: 3,
      },
      text: "+5 STR, +4 VIT, +3 ENE",
      curse: null,
    },
    {
      id: "heart_of_the_wild",
      name: "Heart of the Wild",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        vit: 10,
      },
      text: "+10 VIT",
      curse: null,
    },
    {
      id: "lucky_coin",
      name: "Lucky Coin",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        vit: 2,
        luck: 3,
      },
      text: "+2 VIT · +3 Luck",
      curse: null,
    },
    {
      id: "vanguard_spear",
      name: "Vanguard Spear",
      category: "weapon",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 6,
        dex: 6,
      },
      text: "+6 STR, +6 DEX",
      curse: null,
    },
    {
      id: "shadowstep_boots",
      name: "Shadowstep Boots",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 10,
      },
      text: "+10 DEX",
      curse: null,
    },
    {
      id: "bone_talisman",
      name: "Bone Talisman",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        vit: 7,
        ene: 5,
      },
      text: "+7 VIT, +5 ENE",
      curse: null,
    },
    {
      id: "bloodstone",
      name: "Bloodstone",
      category: "jewelry",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 6,
        vit: 6,
      },
      text: "+6 STR, +6 VIT",
      curse: null,
    },
    {
      id: "rift_compass",
      name: "Rift Compass",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 3,
        luck: 2,
        mimicDetection: 0.08,
      },
      text: "+3 DEX · +2 Luck, +8% phát hiện Mimic",
      curse: null,
    },
    {
      id: "alchemist_belt",
      name: "Alchemist Belt",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        vit: 3,
        potionPower: 0.05,
        potions: 1,
      },
      text: "+3 VIT · +5% hiệu lực bình, +1 bình khi nhận mỗi cấp",
      curse: null,
    },
    {
      id: "guardian_seal",
      name: "Guardian Seal",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        vit: 7,
      },
      text: "+5 STR, +7 VIT",
      curse: null,
    },
    {
      id: "mana_prism",
      name: "Mana Prism",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        ene: 10,
        maxMana: 1,
      },
      text: "+10 ENE · +1 Max MP",
      curse: null,
    },
    {
      id: "goblin_snare",
      name: "Goblin Snare",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 3,
        luck: 1,
        goblinChance: 0.08,
      },
      text: "+3 DEX · +1 Luck, +8% bắt Goblin",
      curse: null,
    },
    {
      id: "wardens_chain",
      name: "Warden’s Chain",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 9,
        dex: -2,
        vit: 5,
      },
      text: "+9 STR, -2 DEX, +5 VIT",
      curse: null,
    },
    {
      id: "moonlit_blade",
      name: "Moonlit Blade",
      category: "weapon",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        ene: 7,
      },
      text: "+5 STR, +7 ENE",
      curse: null,
    },
    {
      id: "assassins_ribbon",
      name: "Assassin’s Ribbon",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 11,
      },
      text: "+11 DEX",
      curse: null,
    },
    {
      id: "lionheart_emblem",
      name: "Lionheart Emblem",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        vit: 8,
      },
      text: "+5 STR, +8 VIT",
      curse: null,
    },
    {
      id: "stormglass",
      name: "Stormglass",
      category: "jewelry",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        dex: 8,
      },
      text: "+5 STR, +8 DEX",
      curse: null,
    },
    {
      id: "saints_ward",
      name: "Saint’s Ward",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 4,
        vit: 3,
        ene: 7,
      },
      text: "+4 STR, +3 VIT, +7 ENE",
      curse: null,
    },
    {
      id: "riftwalkers_boots",
      name: "Riftwalker’s Boots",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 10,
        luck: 1,
      },
      text: "+10 DEX · +1 Luck",
      curse: null,
    },
    {
      id: "executioners_mark",
      name: "Executioner’s Mark",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        dex: 4,
        eliteDamage: 0.12,
      },
      text: "+5 STR, +4 DEX · +12% damage Elite",
      curse: null,
    },
    {
      id: "boss_hunters_badge",
      name: "Boss Hunter’s Badge",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 3,
        vit: 6,
        bossDamage: 0.12,
      },
      text: "+3 STR, +6 VIT · +12% damage Boss",
      curse: null,
    },
    {
      id: "golden_monocle",
      name: "Golden Monocle",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 2,
        mimicDetection: 0.05,
        legendaryFind: 0.03,
      },
      text: "+2 DEX · +5% phát hiện Mimic, +3% tìm SSR",
      curse: null,
    },
    {
      id: "deep_flask",
      name: "Deep Flask",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        vit: 4,
        potionPower: 0.1,
      },
      text: "+4 VIT · +10% hiệu lực bình",
      curse: null,
    },
    {
      id: "war_drums",
      name: "War Drums",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 5,
        dex: 4,
        vit: 3,
      },
      text: "+5 STR, +4 DEX, +3 VIT",
      curse: null,
    },
    {
      id: "spirit_lantern",
      name: "Spirit Lantern",
      category: "utility",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        ene: 10,
        maxMana: 1,
      },
      text: "+10 ENE · +1 Max MP",
      curse: null,
    },
    {
      id: "steel_lotus",
      name: "Steel Lotus",
      category: "armor",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        str: 4,
        dex: 6,
        vit: 3,
      },
      text: "+4 STR, +6 DEX, +3 VIT",
      curse: null,
    },
    {
      id: "fortune_dice",
      name: "Fortune Dice",
      category: "charm",
      rarity: "rare",
      typeCode: "SR",
      catalogVersion: 2,
      effects: {
        dex: 6,
        luck: 4,
      },
      text: "+6 DEX · +4 Luck",
      curse: null,
    },
  ],
  legendary: [
    {
      id: "one_more_hit",
      name: "One More Hit",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        vit: 12,
        escapeTokens: 1,
      },
      text: "+12 VIT · +1 Vé Thoát Hiểm khi nhận mỗi cấp",
      curse: null,
    },
    {
      id: "the_last_bad_decision",
      name: "The Last Bad Decision",
      category: "weapon",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 12,
        dex: 12,
        vit: -5,
      },
      text: "+12 STR, +12 DEX, -5 VIT",
      curse: null,
    },
    {
      id: "wardens_bulwark",
      name: "Warden’s Bulwark",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 10,
        vit: 8,
        ene: 8,
      },
      text: "+10 STR, +8 VIT, +8 ENE",
      curse: null,
    },
    {
      id: "eye_of_rngesus",
      name: "Eye of RNGesus",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 5,
        dex: 5,
        ene: 5,
        luck: 7,
      },
      text: "+5 STR, +5 DEX, +5 ENE · +7 Luck",
      curse: null,
    },
    {
      id: "phoenix_blood",
      name: "Phoenix Blood",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        vit: 16,
        ene: 8,
      },
      text: "+16 VIT, +8 ENE",
      curse: null,
    },
    {
      id: "riftbreaker",
      name: "Riftbreaker",
      category: "weapon",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 12,
        dex: 8,
        bossDamage: 0.2,
        eliteDamage: 0.15,
      },
      text: "+12 STR, +8 DEX · +20% damage Boss, +15% damage Elite",
      curse: null,
    },
    {
      id: "living_armor",
      name: "Living Armor",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 10,
        vit: 16,
      },
      text: "+10 STR, +16 VIT",
      curse: null,
    },
    {
      id: "mimic_crown",
      name: "Mimic Crown",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 6,
        ene: 6,
        luck: 3,
        mimicDetection: 0.2,
        legendaryFind: 0.05,
      },
      text: "+6 DEX, +6 ENE · +3 Luck, +20% phát hiện Mimic, +5% tìm SSR",
      curse: null,
    },
    {
      id: "endless_flask",
      name: "Endless Flask",
      category: "utility",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        vit: 10,
        ene: 8,
        potionPower: 0.2,
        potions: 1,
      },
      text: "+10 VIT, +8 ENE · +20% hiệu lực bình, +1 bình khi nhận mỗi cấp",
      curse: null,
    },
    {
      id: "chrono_shard",
      name: "Chrono Shard",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 20,
        luck: 2,
      },
      text: "+20 DEX · +2 Luck",
      curse: null,
    },
    {
      id: "seraphic_aegis",
      name: "Seraphic Aegis",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 10,
        vit: 6,
        ene: 12,
      },
      text: "+10 STR, +6 VIT, +12 ENE",
      curse: null,
    },
    {
      id: "doomwhisper",
      name: "Doomwhisper",
      category: "weapon",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 14,
        dex: 12,
      },
      text: "+14 STR, +12 DEX",
      curse: null,
    },
    {
      id: "worldroot_seed",
      name: "Worldroot Seed",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 4,
        vit: 22,
      },
      text: "+4 STR, +22 VIT",
      curse: null,
    },
    {
      id: "void_lens",
      name: "Void Lens",
      category: "utility",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 8,
        ene: 8,
        mimicDetection: 0.15,
        legendaryFind: 0.08,
      },
      text: "+8 DEX, +8 ENE · +15% phát hiện Mimic, +8% tìm SSR",
      curse: null,
    },
    {
      id: "angelic_engine",
      name: "Angelic Engine",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        vit: 6,
        ene: 18,
        maxMana: 2,
      },
      text: "+6 VIT, +18 ENE · +2 Max MP",
      curse: null,
    },
    {
      id: "predators_instinct",
      name: "Predator’s Instinct",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 6,
        dex: 14,
        eliteDamage: 0.25,
      },
      text: "+6 STR, +14 DEX · +25% damage Elite",
      curse: null,
    },
    {
      id: "deimoss_scar",
      name: "Deimoss Scar",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 14,
        vit: 6,
        bossDamage: 0.3,
      },
      text: "+14 STR, +6 VIT · +30% damage Boss",
      curse: null,
    },
    {
      id: "golden_goblet",
      name: "Golden Goblet",
      category: "utility",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 6,
        vit: 6,
        luck: 5,
        goblinChance: 0.18,
      },
      text: "+6 DEX, +6 VIT · +5 Luck, +18% bắt Goblin",
      curse: null,
    },
    {
      id: "astral_mail",
      name: "Astral Mail",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 6,
        dex: 8,
        vit: 6,
        ene: 8,
      },
      text: "+6 STR, +8 DEX, +6 VIT, +8 ENE",
      curse: null,
    },
    {
      id: "blood_moon_edge",
      name: "Blood Moon Edge",
      category: "weapon",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 14,
        vit: 12,
      },
      text: "+14 STR, +12 VIT",
      curse: null,
    },
    {
      id: "oracle_mask",
      name: "Oracle Mask",
      category: "armor",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 12,
        ene: 10,
        luck: 5,
      },
      text: "+12 DEX, +10 ENE · +5 Luck",
      curse: null,
    },
    {
      id: "eternal_clover",
      name: "Eternal Clover",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        dex: 4,
        vit: 4,
        luck: 9,
        legendaryFind: 0.04,
      },
      text: "+4 DEX, +4 VIT · +9 Luck, +4% tìm SSR",
      curse: null,
    },
    {
      id: "titan_heart",
      name: "Titan Heart",
      category: "charm",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 6,
        vit: 22,
      },
      text: "+6 STR, +22 VIT",
      curse: null,
    },
    {
      id: "sevenfold_sigil",
      name: "Sevenfold Sigil",
      category: "jewelry",
      rarity: "legendary",
      typeCode: "SSR",
      catalogVersion: 2,
      effects: {
        str: 7,
        dex: 7,
        vit: 7,
        ene: 7,
        luck: 3,
      },
      text: "+7 STR, +7 DEX, +7 VIT, +7 ENE · +3 Luck",
      curse: null,
    },
  ],
  cursed: [
    {
      id: "glass_cannon",
      name: "Glass Cannon",
      category: "weapon",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 35,
        dex: 15,
      },
      text: "+35 STR, +15 DEX",
      curse: {
        id: "glass_cannon_curse",
        effects: {
          defenseSet: 0,
        },
        text: "Defense = 0",
      },
    },
    {
      id: "schrodingers_armor",
      name: "Schrödinger’s Armor",
      category: "armor",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 20,
        vit: 30,
      },
      text: "+20 STR, +30 VIT",
      curse: {
        id: "schrodingers_armor_curse",
        effects: {
          vit: -12,
        },
        text: "-12 VIT",
      },
    },
    {
      id: "goblins_debt",
      name: "Goblin’s Debt",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        dex: 20,
        vit: 15,
        luck: 12,
        goblinChance: 0.2,
      },
      text: "+20 DEX, +15 VIT · +12 Luck, +20% bắt Goblin",
      curse: {
        id: "goblins_debt_curse",
        effects: {
          bonusPenalty: 0.15,
        },
        text: "mất 15% payout hiện tại mỗi cấp nhận",
      },
    },
    {
      id: "crown_of_ruin",
      name: "Crown of Ruin",
      category: "armor",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 20,
        vit: 15,
        luck: 8,
      },
      text: "+20 STR, +15 VIT · +8 Luck",
      curse: {
        id: "crown_of_ruin_curse",
        effects: {
          bonusPenalty: 0.1,
        },
        text: "mất 10% payout hiện tại mỗi cấp nhận",
      },
    },
    {
      id: "blood_pact",
      name: "Blood Pact",
      category: "weapon",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 40,
        dex: 10,
      },
      text: "+40 STR, +10 DEX",
      curse: {
        id: "blood_pact_curse",
        effects: {
          vit: -15,
        },
        text: "-15 VIT",
      },
    },
    {
      id: "void_heart",
      name: "Void Heart",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        vit: 35,
        ene: 20,
      },
      text: "+35 VIT, +20 ENE",
      curse: {
        id: "void_heart_curse",
        effects: {
          potionPower: -0.15,
        },
        text: "-15% hiệu lực bình",
      },
    },
    {
      id: "broken_hourglass",
      name: "Broken Hourglass",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        dex: 40,
        luck: 8,
      },
      text: "+40 DEX · +8 Luck",
      curse: {
        id: "broken_hourglass_curse",
        effects: {
          floorHpLoss: 0.04,
        },
        text: "mất 4% Max HP sau mỗi tầng",
      },
    },
    {
      id: "mimics_promise",
      name: "Mimic’s Promise",
      category: "utility",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        dex: 20,
        ene: 15,
        mimicDetection: 0.1,
        legendaryFind: 0.12,
      },
      text: "+20 DEX, +15 ENE · +10% phát hiện Mimic, +12% tìm SSR",
      curse: {
        id: "mimics_promise_curse",
        effects: {
          mimicChance: 0.12,
        },
        text: "+12% Mimic",
      },
    },
    {
      id: "berserker_chains",
      name: "Berserker Chains",
      category: "weapon",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 40,
        dex: 10,
        eliteDamage: 0.2,
      },
      text: "+40 STR, +10 DEX · +20% damage Elite",
      curse: {
        id: "berserker_chains_curse",
        effects: {
          damageTaken: 0.18,
        },
        text: "nhận thêm 18% damage",
      },
    },
    {
      id: "hollow_crown",
      name: "Hollow Crown",
      category: "armor",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        vit: 10,
        ene: 40,
        maxMana: 2,
      },
      text: "+10 VIT, +40 ENE · +2 Max MP",
      curse: {
        id: "hollow_crown_curse",
        effects: {
          str: -15,
        },
        text: "-15 STR",
      },
    },
    {
      id: "ashen_wings",
      name: "Ashen Wings",
      category: "armor",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        dex: 40,
        ene: 10,
      },
      text: "+40 DEX, +10 ENE",
      curse: {
        id: "ashen_wings_curse",
        effects: {
          resistance: -20,
        },
        text: "-20 Resistance",
      },
    },
    {
      id: "soul_leash",
      name: "Soul Leash",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 20,
        ene: 25,
        bossDamage: 0.35,
      },
      text: "+20 STR, +25 ENE · +35% damage Boss",
      curse: {
        id: "soul_leash_curse",
        effects: {
          maxMana: -2,
        },
        text: "-2 Max MP",
      },
    },
    {
      id: "bleeding_star",
      name: "Bleeding Star",
      category: "jewelry",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 20,
        dex: 30,
      },
      text: "+20 STR, +30 DEX",
      curse: {
        id: "bleeding_star_curse",
        effects: {
          floorHpLoss: 0.06,
        },
        text: "mất 6% Max HP sau mỗi tầng",
      },
    },
    {
      id: "null_idol",
      name: "Null Idol",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 20,
        vit: 15,
        ene: 20,
      },
      text: "+20 STR, +15 VIT, +20 ENE",
      curse: {
        id: "null_idol_curse",
        effects: {
          dex: -15,
          luck: -6,
        },
        text: "-15 DEX, -6 Luck",
      },
    },
    {
      id: "black_sun",
      name: "Black Sun",
      category: "charm",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        dex: 10,
        ene: 30,
        luck: 10,
        legendaryFind: 0.15,
      },
      text: "+10 DEX, +30 ENE · +10 Luck, +15% tìm SSR",
      curse: {
        id: "black_sun_curse",
        effects: {
          potionPower: -0.2,
        },
        text: "-20% hiệu lực bình",
      },
    },
    {
      id: "oathbreaker",
      name: "Oathbreaker",
      category: "weapon",
      rarity: "cursed",
      typeCode: "UR",
      catalogVersion: 2,
      effects: {
        str: 25,
        dex: 15,
        vit: 10,
        bossDamage: 0.25,
        eliteDamage: 0.25,
      },
      text: "+25 STR, +15 DEX, +10 VIT · +25% damage Boss, +25% damage Elite",
      curse: {
        id: "oathbreaker_curse",
        effects: {
          str: -10,
          dex: -10,
        },
        text: "-10 STR, -10 DEX",
      },
    },
  ],
};
const TYPE_CODES = Object.freeze({
  common: "R",
  rare: "SR",
  legendary: "SSR",
  cursed: "UR",
});
function validateItems(catalog = ITEMS) {
  const ids = new Set();
  for (const [rarity, count] of Object.entries({
    common: 32,
    rare: 28,
    legendary: 24,
    cursed: 16,
  })) {
    if (catalog[rarity]?.length !== count)
      throw new Error("INVALID_HARDCORE_ITEM_COUNT");
    for (const item of catalog[rarity]) {
      if (
        ids.has(item.id) ||
        item.rarity !== rarity ||
        !Object.keys(item.effects).length ||
        (rarity === "cursed" && !Object.keys(item.curse?.effects || {}).length)
      )
        throw new Error("INVALID_HARDCORE_ITEM:" + item.id);
      for (const value of Object.values({
        ...item.effects,
        ...item.curse?.effects,
      }))
        if (!Number.isFinite(value)) throw new Error("INVALID_HARDCORE_EFFECT");
      ids.add(item.id);
    }
  }
  return true;
}
validateItems();
for (const pool of Object.values(ITEMS)) {
  for (const item of pool) {
    Object.freeze(item.effects);
    if (item.curse) {
      Object.freeze(item.curse.effects);
      Object.freeze(item.curse);
    }
    Object.freeze(item);
  }
  Object.freeze(pool);
}
Object.freeze(ITEMS);
module.exports = { ITEMS, TYPE_CODES, validateItems };
